pipeline:
  build:
    image: python
    commands:
      - curl -O https://bootstrap.pypa.io/get-pip.py
      - python get-pip.py
      - pip install -r requirements.txt
      - pip install -r requirements-dev.txt
      - tox -e py27
      - tox -e py36
