image: python

stages:
- test
- build

before_script:
- curl -O https://bootstrap.pypa.io/get-pip.py
- python get-pip.py
- pip install -r requirements.txt
- pip install -r requirements-dev.txt

python36:
  image: python:3.6
  stage: test
  script: tox -e py36
