# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: sculpto/python2-and-3

pipelines:
  default:
    - step:
        name: Preparing
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - pip install -r requirements-dev.txt

    - step:
        name: Python 2.7
        script:
          - tox -e py27

    - step:
        name: Python 3.6
        script:
          - tox -e py36
