version: "3"

# Services
services:

  # Portainer service: Docker web interface
  portainer:
    # Path to image (always "images/*")
    build: images/portainer/
    # Image tag
    image: localhost:5000/sample01_portainer
    volumes:
      standard:
        - portainer:/data
        - /var/run/docker.sock:/var/run/docker.sock
        - ""
      static:
        - portainer/test.txt:/test.txt
        - ""
      shared:
        - toto:/toto
        - ""
      templates:
        - portainer/template-test.txt.j2:/template-test.txt
        - portainer/bash-test.sh.j2:/bash.sh
        - ""
    ports:
      - "{{ PORTAINER_OUTPUT_PORT }}:9000"
    networks:
      net:
        aliases:
          - portainer

    restart: on-failure

  # Hello world
  hello-world:
    # Path to image
    build: images/app/hello-world
    # Image tag
    image: localhost:5000/sample01_helloworld

volumes:
  portainer:

networks:
  net:
